ifeq ($(CONFIG_SENSOR_HS300X_TEMPERATURE),y)
	SRC_DIR += hs300x_temp
endif

ifeq ($(CONFIG_SENSOR_DHT22_TEMPERATURE),y)
	SRC_DIR += dht22_temp
endif

ifeq ($(CONFIG_SENSOR_SHT20_TEMPERATURE),y)
	SRC_DIR += sht20_temp
endif


include $(KERNEL_ROOT)/compiler.mk
